### ISSUE TITLE
[PE-D][Tester D] Error in allow adding an event with a date in the past

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T10-3/tp#106]
![image.png](https://raw.githubusercontent.com/jessicawyz/ped/main/files/4edb6d85-1c81-44b9-b02f-2d1172ea58c2.png)

This app should not allow the addition of an event in the past.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: jessicawyz/ped#2

**Comment by ChocoRagdoll** [comment]
The app can be a record for past event also so :)
