### ISSUE TITLE
[PE-D][Tester C] Tags are not exported

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T10-3/tp#153]
**Steps to reproduce:**
1. Select an event that has participants, eg ```sel 2```
2. Enter the command, ```export n/ a/ p/ t/```
3. Check the csv file

**Expected:**
The tags should be exported along with the other details.

**Actual:**
Everything except tags are exported.

**Screenshots:**
_(By order of steps to reproduce)_
1. 
![image.png](https://raw.githubusercontent.com/Teee728/ped/main/files/7a858502-e437-452b-9d47-adb2f91d303d.png)
2. 
![image.png](https://raw.githubusercontent.com/Teee728/ped/main/files/853ff5a8-6b4d-4215-8ef2-6afc6793fc06.png)
3. 
![image.png](https://raw.githubusercontent.com/Teee728/ped/main/files/24134622-3551-4cf8-a3e4-5eebb9d30107.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: Teee728/ped#11

**Comment by Apzure** [comment]
Imo, we should just specify in the UG that we don't allow for exporting of tags.

**Comment by ChocoRagdoll** [comment]
The exporting of tags has privacy concerns and is rarely used by the target users, so we decided not to include it in our application.
